### ISSUE TITLE
Change in behavior in wrapper around "devtools::install_github"

### ISSUE THREAD

**Issue by StuartWheater** [obiba/opal#3433]
**Describe the bug**
Change in behavior by wrapper around "devtools::install_github"

**Expected behavior**

Previous coding (2.12.2):

private String getInstallGitHubCommand(String name, String username, String ref) {
    return "devtools::install_github('" + name + "', username='" + username + "', ref='" + ref + "')";
}

has become:

private String getInstallGitHubCommand(String name, String username, String ref) {
    return String.format("devtools::install_github('%s/%s', ref='%s')", username, name, ref);
}

I realise "username: User name. Deprecated: please include username in the repo" in devtools > 2.0.
So is this change in behavior intentional, and the behavior going forward?

**Comment by ymarcon** [comment]
Correct me if I am wrong but the 2nd statement is the one expected, i.e. without `username` parameter call.

**Comment by StuartWheater** [comment]
The mini-problem I have is that 'name' was effectively an alias for 'repo' and before contained '/datashield/dsBetaTest', and username ('datashield') was ignored.  Now I end-up with a repo of '/datashield/datashield/dsBetaTest'.

**Comment by ymarcon** [comment]
Ok there was a confusion here. You were using a workaround for handling the deprecated devtools API that was implemented in opal 2.12 and lower. And while doing this, it added a new feature in Opal which is the ability to install a package not belonging to the `datashield` github user/organisation name (this username is hard-coded on the server side). By fixing the need of this workaround, the side effect of the new feature was lost.

I propose to introduce the following behaviour:
* if the repository name is fully qualified (i.e. with a `/`, like in `someUser/dsBetaTest`) then let devtools go with it,
* otherwise, append `datashield` to the repo short name (i.e. `dsBetaTest` will become `datashield/dsBetaTest`)

**Comment by StuartWheater** [comment]
On a slightly related note, if you use the "Add DataSHIELD Package" dialog on the Opal Web Portal, is the username 'datashield' assumed?

**Comment by ymarcon** [comment]
Yes it was assumed (and also constrained). With the fix I have pushed, one could provide `someUser/somePackage` or just `somePackage` (that would be expanded to `datashield/somePackage`).

**Comment by StuartWheater** [comment]
Thanks. I often deploy DataSHIELD packages from non-standard location, and that will be of great help.
