### ISSUE TITLE
Invalid typecast of 'null' entries in date variable (R client) 

### ISSUE THREAD

**Issue by abhishekdxt** [obiba/opal#3435]
This issue is in relation to Opal R client  2.6.0.

Basically, null entries from a 'Date' variable when exported using R client show up as '-5877641-06-23'.

For example, opal table 'Demographics' contains a variable 'DeathDate' with some entries null.

| ID  | DeathDate |
| ------------- | ------------- |
| 1  | 1970-01-06  |
| 2  | null  |
| 3  | 1970-01-12  |
| 4  | null  |
| 5  | 1970-02-22  |

Upon exporting this data via R I see the following:

 | ID  | DeathDate |
| ------------- | ------------- |
| 1  | 1970-01-06  |
| 2  | -5877641-06-23  |
| 3  | 1970-01-12  |
| 4  | -5877641-06-23  |
| 5  | 1970-02-22  |

**Comment by kkmann** [comment]
I doubt that this is a client-side problem. I was using 2.6.0 since quite a while from the offical https://github.com/obiba/cran/tree/gh-pages/src/contrib repository. Hasn't changed in a year. The issue must have been introduced between mid-November and now, probably server-side. Kinda makes sense to me since the data frames are created server side, right?

**Comment by ymarcon** [comment]
The fix for #3434 changed values from integers to doubles for building a Date object. But the double flavor for NA was also to be used...

**Comment by kkmann** [comment]
@ymarcon could you put together a quick bugfix release including this one?

**Comment by ymarcon** [comment]
Will do. Tomorrow...

Le jeu. 31 janv. 2019 à 23:38, Kevin Kunzmann <notifications@github.com> a
écrit :
