### ISSUE TITLE
Version control on tables

### ISSUE THREAD

**Issue by sidohaakma** [obiba/opal#3489]
**Problem**
Now managing different version of the data dictionary used by a consortium is hard to realise. The solution now is to make a new table for each new version of the data dictionary. We can use that specific table in solving a research question in DataSHIELD.

A new version of the data dictionary could involve:
- new variables amended to the old dictionary
- existing variables changed
- existing variables removed

**Solution**
*How to deal with data dictionaries*
When you upload a new version a data dictionary this would not create a new table in Opal but will amend changes to the existing one. Just like github it needs to have a reference to the old table and the new one. This should also be available in DataSHIELD. So you need to be able to point out which table you want to use. 

*How to deal with data*
- When want to be able to amend the data as well. For instance in case of amended variables. 
- If the new data dictionary involves changes that cannot be handled by Opal the dictionary cannot be create as a new version of the table. So for instance when you want to convert from string to integer and the values contain string types Opal cannot accept it.

**Alternatives**
Check the problem statement. This includes the current workaround.

**Additional context**
I do not know if other people have had the same question? This is what we could think of at the moment as possible direction of solving this problem. The solution needs more work, but maybe we could talk offline to sharpen the solution a bit more.

**Comment by ymarcon** [comment]
Have you tried with views? view can be used to amend data dictionary (in the view, not in the raw table), to change data types (derivation script can do it) and to update data (by changing the table referred by the view).

**Comment by sidohaakma** [comment]
Hi Yannick,

Sorry it took so long. The problem is a bit more clear now. 
LifeCycle is organised a bit different than other projects as far as I know. Interconnect and Recap for instance harmonise mostly on the basis of research question. So variables are harmonised to solve a certain problem. 

LifeCycle wants to expose a set of data which can be used to solve all kinds of research questions. A bit of the other way around. We encounter at the moment that a lot of changes are made in the data types and naming of the variables in the data dictionaries. That will be done in the future as well. Dropping and amending the core set will also happen. 

As far as I know those changes can not be made in views, but have to be done in the data dictionary itself. When research has been done on the set that was available at a certain timepoint and changes are made to the variables in the meantime, how do you get back to that specific set to reproduce the research?

Is that possible to solve this with views?

Kind regards,

Sido

**Comment by ymarcon** [comment]
You should make "releases" of the dataset. The datasets that are being modified (data update and/or dictionary update) are like a development branch and should not be used by researchers. Once this dev branch is stable, make a release (copy datasets in a project with a release number/date timestamp in its name for instance), and make them available for researchers. Once finished, archive this project (detach opal project from database or export in files) and repeat.

If you think about versioning like storing diffs of the datasets on each commit, this won't be done in opal, because it is too much complexity. The only versioning we have is on the views, because views have a textual representation (of the table logic, not of the data) and you can diff the changes.
