### ISSUE TITLE
Use Elixir AAI authentication and authorisation service

### ISSUE THREAD

**Issue by tombisho** [obiba/opal#3507]
The long term vision for EUCAN-Connect is to use a central authentication service, according to our grant proposal.

The suggested solution is to use [Elixir AAI](https://elixir-europe.org/services/compute/aai). I can see that this whole thing is not trivial, but at least wanted to put a placeholder in here. For example, would it make sense to also integrate other OBiBa applications such as Mica. In some ways this could be an alternative to Agate?

**Comment by ymarcon** [comment]
According to the [Development Guide for ELIXIR OIDC](https://docs.google.com/document/d/1vOyW4dLVozy7oQvINYxHheVaLvwNsvvghbiKTLg7RbY/edit), Elixir identity provider service can be used through the OpenID Connect protocol, which is supported by Opal (since 2.14) and will be supported by Agate/Mica (1.5, to be released this month).

[OpenID Connect](https://openid.net/connect/) is suitable for manual login, but it is less convenient for scripting (I am thinking of a R/DataSHIELD script).

**Comment by ymarcon** [comment]
The feature #3508 could be a solution for separating the manual login (possibly through openid) from the application login.

**Comment by ymarcon** [comment]
I have registered a Opal (test) instance as a OpenId client of Elixir and it works well. Need to verify how to define and retrieve "groups" from Elixir so that appropriate permissions are applied in Opal.

**Comment by ymarcon** [comment]
The new feature #3508 is actually the only way for OpenID users to connect to Opal. The support of personal access tokens has also been added to the DSI and DSOpal for use in Datashield context.

**Comment by ymarcon** [comment]
See documentation about [Personal access tokens](http://opaldoc.obiba.org/en/dev/web-user-guide/my-profile.html#personal-access-tokens).
