### ISSUE TITLE
Opal installation issue (Windows)

### ISSUE THREAD

**Issue by mennodekker** [obiba/opal#3622]
I tried to install Opal in a Windows system. I have downloaded openjdk-8u41 and unzipped it. By using google I found that I needed to replace the cacert file with that from a newer package. So I did.

Then i downloaded Opal and unzipped id. Set the opal-home dir, java home and tried to run it. While it shows no error in the log, and does fire up some kind of webserver. Then I go to localhost:8080 and it always shows 
HTTP ERROR 404 Problem accessing /. Reason:   Not Found
The server is running, when i shut it down i get an empty no connection page.

I tried installing Agate the same way and it shows me a login and works out of the box. I feel really stupid, but what am I missing here for Opal?

**Comment by ymarcon** [comment]
Is it for testing purpose that you want to install Opal on Windows? With the time Opal has got even more dependent on the R server in the backend and I feel like you will face more trouble. You should switch to the docker option instead, it will be more reliable.

**Comment by mennodekker** [comment]
Yes, it is just for testing. We want do to a quick POC to see if Opal can help us the way we expect it to do before we start the circus of getting one or more linux servers for a production deploy. Since Agate installed without problems I feel there must be something small I am missing.

**Comment by hjvdwijk** [comment]
The issue is with the file path, that must start with 3 slashes. Could you change this in de code?

The other issue is on URL’s for file, these need three slashes file:///
https://stackoverflow.com/questions/6098472/pass-a-local-file-in-to-url-in-java/6098521 
https://en.wikipedia.org/wiki/File_URI_scheme 

A file URI takes the form of
file://host/path
, where host is the fully qualified domain name of the system on which the path is accessible, and path is a hierarchical directory path of the form directory/directory/.../name. If host is omitted, it is taken to be "localhost", the machine from which the URL is being interpreted. Note that when omitting host, the slash is not omitted (while "file:///foo.txt" is valid, "file://foo.txt" is not, although some interpreters manage to handle the latter).


private Handler createDistFileHandler(String directory) throws IOException, URISyntaxException {
  return createFileHandler(**"file:///"** + resolveOpalDistPath() + directory);
}

private Handler createFileHandler(String fileUrl) throws IOException, URISyntaxException {
  log.info("Creating a file handler for the following URL : {}", fileUrl);
  ResourceHandler resourceHandler = new ResourceHandler();
  resourceHandler.setBaseResource(new PathResource(new URL(fileUrl)));
  resourceHandler.setRedirectWelcome(true);

  GzipHandler gzipHandler = new GzipHandler();
  gzipHandler.setHandler(resourceHandler);
  gzipHandler.setIncludedMimeTypes(GZIP_MIME_TYPES);

  return gzipHandler;
}

private Handler createExtensionFileHandler(String filePath) throws IOException, URISyntaxException {
  File file = new File(filePath);
  if (!file.exists() && !file.mkdirs()) {
    throw new RuntimeException("Cannot create extensions directory: " + file.getAbsolutePath());
  }
  return createFileHandler(**"file:///"** + filePath);
}

**Comment by ymarcon** [comment]
Protocol prefix `file://` is the correct syntax for URIs. The problem is that the file system path that follows must start with a `/`. That is the case on unix's absolute file path. In the case of windows, it may start the drive letter instead of a slash. The change ensures that the absolute file path starts with `/`.

But again, you should use docker on your windows machine.
