### ISSUE TITLE
PAT expiration time

### ISSUE THREAD

**Issue by meteakgun** [obiba/opal#3626]
In our project, we use Keycloak for user management. If we delete a user account from Keycloak, we have to delete the corresponding account in OPAL manually. If we don't delete the corresponding account in OPAL, the PATs generated from this account are still valid and can be used to access services. 

One possible solution is setting an expiration time for PATs. In the current version, the administrator can not set an expiration time for PATs. If we can implement this feature, this makes OPAL more secure against the situation I described above. 

Thanks.

**Comment by ymarcon** [comment]
There could be two reasons why a token would expire:
* it has not been used for a while (ex: token is invalidated because it was not used in the last 30 days) 
* it has reached an absolute end-of-life date (ex: token is invalidated after 1 year)

The 2 can be combined of course. These timeout values are defined at system level (and are not mandatory).

**Comment by meteakgun** [comment]
Can we change the expiration time for PATs? For example, they expire after 8 hours.  I think this will be a very important improvement in terms of security.

**Comment by meteakgun** [comment]
I mean we would like to change the absolute end-of-life date of PATs at system level.

**Comment by ymarcon** [comment]
This is a feature request. The comment was about detailing it.
