### ISSUE TITLE
Table export using haven 2.4.x causes type errors

### ISSUE THREAD

**Issue by kazoompa** [obiba/opal#3629]
Exporting Opal tables via the latest version tidyverse/haven (2.4.x) generates the following error:

```
org.obiba.opal.spi.r.RRuntimeException: Error while evaluating 'base::is.null(haven::write_sav(`file2e575eee35`, path='file2e575eee35.sav', compress=FALSE))' -> Error : Invalid input type, expected 'integer' actual 'double'
```

To recreate the error run the [export unit test](https://github.com/obiba/opalr/blob/master/tests/testthat/test-table.R#L1)

See haven issue: https://github.com/tidyverse/haven/issues/595

**Comment by iago-pssjd** [comment]
Dear @ymarcon,

Coincidentally, I got the issue https://github.com/tidyverse/haven/issues/595#issue-876415125  after downloading a harmonized database from opal.pssjd.org and trying to save it.

Then, as the labels are specified through the Dataschema excel files, I was wondering if could we make that the labels type in these files be the right one or if there is any other way through OPAL to avoid that issue, without having to use haven 2.3.1 (and so that when we download the data, it has already consistent label and data types).

Thank you!

**Comment by ymarcon** [comment]
Hi, the fix is included in Opal 4.1.1 (latest) since yesterday's evening :)

**Comment by iago-pssjd** [comment]
Yes, thanks! I should have specified I meant with previous OPAL versions, could we do something through Dataschemas or manipulating the labels or we will get this behaviour with any OPAL < 4.1.1?

**Comment by ymarcon** [comment]
We are not making releases of older versions. It's too much work and it is useless as we ensure Opal backward compatibility.
