### ISSUE TITLE
Authentication problems with user with "Add project" permissions.

### ISSUE THREAD

**Issue by djuarezgf** [obiba/opal#3817]
### This issue is unique

- [X] I have used the [search tool](https://github.com/obiba/Opal/issues?q=) and did not find an issue describing my bug.

### Version information

4.6

### Expected behavior

I am trying to execute the following command:
opal project --opal http://localhost:8080/opal --user projectUser --password XXXXXX  --name myProject
"projectUser" has "Add Project" permissions.
However, after executing this command, Opal requires the password again (Enter password:)

If I try the same with an administrator user, everything goes fine:
opal project --opal http://localhost:8080/opal --user administrator --password XXXXXX  --name myProject

For any project operation with "projectUser", Opal always requires the password again. I call it programmatically so that I get in the logs always the following message:
{"code": 403, "status": "Forbidden: Request forbidden -- authorization will not help"}

However, Opal allows "projectUser" to create projects and import data.
Is it possible to fix this issue, so that I don't get any error message from Opal? Or am I missing something?

### Operating System (OS)

Linux

### Browser

Google Chrome

### Contact info

- German Cancer Research Center

**Comment by ymarcon** [comment]
If you want to add a project, you must specify the option `--add`. Without this option your command tries to get the details of a project (that does not exists).
https://opaldoc.obiba.org/en/latest/python-user-guide/project/project.html

If you are using the `--password`, make sure to escape the special characters that could be misinterpreted by the shell. In addition to that, it is a bad practice to have your password in the command line because it will be in your shell history. It is also bad to have it in a script file: you should use a Personal Access Token instead.
https://opaldoc.obiba.org/en/latest/web-user-guide/my-profile.html#personal-access-tokens

**Comment by djuarezgf** [comment]
We try to check if the project exists, before creating it. Is this possible with the "Add project" permission?

Regarding the password, it is a second program that calls the opal client sending the password. But the password is never logged.

**Comment by ymarcon** [comment]
A user with the "Add project" permission will only projects he has created or he was granted access permission to.

There is no second program.
