### ISSUE TITLE
Cannot generate identifiers

### ISSUE THREAD

**Issue by ymarcon** [obiba/opal#3913]
The arguments of `identifiersStore.generateMapping()` are wrong:

![image](https://github.com/user-attachments/assets/e8d5110a-d927-4d30-a63a-155e59bca569)

**Comment by ymarcon** [comment]
Note: no database for ids was defined and when I went on the identifiers page I got an ugly error. Then I registered a database for ids and got this error using the built-in Participant. For some reasons something went wrong.

**Comment by kazoompa** [comment]
I will check it out. I review and use the entiry type rather than the table name. All my tests past, I guess, if the table name is not the same you may have this issue although I do not know how the name will be different since when you create one there is only one Input for the Entity Type which is also the name of the table. TBV
